# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_Racheal_Dheeraj.xci
# IP: The module: 'ila_Racheal_Dheeraj' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_Racheal_Dheeraj'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_Racheal_Dheeraj'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_Racheal_Dheeraj_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_Racheal_Dheeraj'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_Racheal_Dheeraj.xci
# IP: The module: 'ila_Racheal_Dheeraj' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_Racheal_Dheeraj'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_Racheal_Dheeraj'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rache_000/Desktop/detour_project/detour_project.srcs/sources_1/ip/ila_Racheal_Dheeraj/ila_Racheal_Dheeraj_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_Racheal_Dheeraj'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
